### ISSUE TITLE
Add support for MathJax and the LaTeX notation

### ISSUE THREAD

**Issue by powerman** [KyleKing/mdformat-obsidian#2]
Current version breaks example from https://help.obsidian.md/Editing+and+formatting/Advanced+formatting+syntax#Math:

```diff
 $$
-\begin{vmatrix}a & b\\
+\\begin{vmatrix}a & b\\
 c & d
-\end{vmatrix}=ad-bc
+\\end{vmatrix}=ad-bc
 $$
```
Was:
![изображение](https://github.com/user-attachments/assets/37244b40-a47c-4289-ad56-f7dcca7c03a0)
Now:
![изображение](https://github.com/user-attachments/assets/1c7dcc73-1237-44e7-b89d-c4ee60034e80)

**Comment by KyleKing** [comment]
`mdformat-myst` appears to support dollar math. If you have a chance, it might be worth trying: https://github.com/executablebooks/mdformat-myst (See: https://myst-parser.readthedocs.io/en/latest/syntax/math.html#dollar-delimited-math)

If `mdformat-myst` works, we can either incorporate a small portion of the logic into `mdformat-obsidian` or making `mdformat-myst` an optional extra when users need to render math

**Comment by powerman** [comment]
Well, `myst` works. It conflicts with `footnote` plugin and a bit differently format `%%` block commens. Still, using it for this reason (obsidian math support) feels like a real overkill.
