### ISSUE TITLE
Add support for unfolded callouts

### ISSUE THREAD

**Issue by powerman** [KyleKing/mdformat-obsidian#4]
Current version breaks unfolded callouts documented at https://help.obsidian.md/Editing+and+formatting/Callouts#Foldable+callouts:

```diff
 
-> [!faq]- Are callouts foldable?
+> [!FAQ]- Are callouts foldable?
 > Yes! In a foldable callout, the contents are hidden when the callout is collapsed.
 
-> [!faq]+ Are callouts foldable?
+> [!FAQ]
 > Yes! In a foldable callout, the contents are hidden when the callout is collapsed.
 
```

Was:
![изображение](https://github.com/user-attachments/assets/84f8ee3a-fe85-479e-9c67-a2e223d1c6a1)
Now:
![изображение](https://github.com/user-attachments/assets/75889efe-0180-4390-a636-96a50dddfbe3)

**Comment by KyleKing** [comment]
I missed adding a test case for "+"! That has now been fixed and included in v0.0.3 (https://github.com/KyleKing/mdformat-obsidian/commit/afc08b2ee030b167a5ce555eb11c5aef933239e3)

I'll continue to work through the other issues when I have time over the next week or two
